"""
Seed script — inserts ~500 books across multiple genres into the library database.
Run from the backend directory:
  "C:\Program Files\Python310\python.exe" seed_books.py
"""

import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "library.db")

BOOKS = [
    # ── FICTION ──────────────────────────────────────────────────────────────
    ("To Kill a Mockingbird",               "Harper Lee",                    "Fiction",    "978-0-06-112008-4", "Available"),
    ("1984",                                "George Orwell",                 "Fiction",    "978-0-45-152493-5", "Available"),
    ("Pride and Prejudice",                 "Jane Austen",                   "Fiction",    "978-0-14-143951-8", "Available"),
    ("The Great Gatsby",                    "F. Scott Fitzgerald",           "Fiction",    "978-0-74-321356-5", "Available"),
    ("Of Mice and Men",                     "John Steinbeck",                "Fiction",    "978-0-14-028862-8", "Available"),
    ("The Catcher in the Rye",              "J.D. Salinger",                 "Fiction",    "978-0-31-676948-0", "Available"),
    ("Brave New World",                     "Aldous Huxley",                 "Fiction",    "978-0-06-092987-5", "Available"),
    ("Lord of the Flies",                   "William Golding",               "Fiction",    "978-0-57-112070-0", "Available"),
    ("Crime and Punishment",                "Fyodor Dostoevsky",             "Fiction",    "978-0-14-044913-6", "Available"),
    ("Anna Karenina",                       "Leo Tolstoy",                   "Fiction",    "978-0-14-303500-7", "Available"),
    ("The Brothers Karamazov",              "Fyodor Dostoevsky",             "Fiction",    "978-0-37-472108-7", "Available"),
    ("War and Peace",                       "Leo Tolstoy",                   "Fiction",    "978-0-14-044793-4", "Available"),
    ("Moby-Dick",                           "Herman Melville",               "Fiction",    "978-0-14-243723-0", "Available"),
    ("The Adventures of Huckleberry Finn",  "Mark Twain",                    "Fiction",    "978-0-14-028329-6", "Available"),
    ("Don Quixote",                         "Miguel de Cervantes",           "Fiction",    "978-0-14-244940-0", "Available"),
    ("Jane Eyre",                           "Charlotte Brontë",              "Fiction",    "978-0-14-144114-6", "Available"),
    ("Wuthering Heights",                   "Emily Brontë",                  "Fiction",    "978-0-14-143955-6", "Available"),
    ("The Picture of Dorian Gray",          "Oscar Wilde",                   "Fiction",    "978-0-14-143957-0", "Available"),
    ("Great Expectations",                  "Charles Dickens",               "Fiction",    "978-0-14-143956-3", "Available"),
    ("A Tale of Two Cities",                "Charles Dickens",               "Fiction",    "978-0-14-143960-0", "Available"),
    ("The Scarlet Letter",                  "Nathaniel Hawthorne",           "Fiction",    "978-0-14-039003-8", "Available"),
    ("Middlemarch",                         "George Eliot",                  "Fiction",    "978-0-14-043388-6", "Available"),
    ("Ulysses",                             "James Joyce",                   "Fiction",    "978-0-67-972020-1", "Available"),
    ("Beloved",                             "Toni Morrison",                 "Fiction",    "978-1-40-003342-3", "Available"),
    ("One Hundred Years of Solitude",       "Gabriel García Márquez",        "Fiction",    "978-0-06-088328-7", "Available"),
    ("The Alchemist",                       "Paulo Coelho",                  "Fiction",    "978-0-06-231609-7", "Available"),
    ("Life of Pi",                          "Yann Martel",                   "Fiction",    "978-0-15-602732-3", "Available"),
    ("The Kite Runner",                     "Khaled Hosseini",               "Fiction",    "978-1-59-463193-1", "Available"),
    ("A Thousand Splendid Suns",            "Khaled Hosseini",               "Fiction",    "978-1-59-463180-1", "Available"),
    ("The Road",                            "Cormac McCarthy",               "Fiction",    "978-0-30-726543-2", "Available"),
    ("East of Eden",                        "John Steinbeck",                "Fiction",    "978-0-14-028339-5", "Available"),
    ("The Grapes of Wrath",                 "John Steinbeck",                "Fiction",    "978-0-14-303943-3", "Available"),
    ("For Whom the Bell Tolls",             "Ernest Hemingway",              "Fiction",    "978-0-68-480336-3", "Available"),
    ("A Farewell to Arms",                  "Ernest Hemingway",              "Fiction",    "978-0-68-480462-9", "Available"),
    ("The Sun Also Rises",                  "Ernest Hemingway",              "Fiction",    "978-0-74-322886-6", "Available"),
    ("Their Eyes Were Watching God",        "Zora Neale Hurston",            "Fiction",    "978-0-06-093141-0", "Available"),
    ("The Color Purple",                    "Alice Walker",                  "Fiction",    "978-0-15-619153-3", "Available"),
    ("Mrs Dalloway",                        "Virginia Woolf",                "Fiction",    "978-0-15-662892-4", "Available"),
    ("To the Lighthouse",                   "Virginia Woolf",                "Fiction",    "978-0-15-690739-7", "Available"),
    ("The Stranger",                        "Albert Camus",                  "Fiction",    "978-0-67-972020-5", "Available"),
    ("The Plague",                          "Albert Camus",                  "Fiction",    "978-0-67-972020-6", "Available"),
    ("Nausea",                              "Jean-Paul Sartre",              "Fiction",    "978-0-81-120831-7", "Available"),
    ("Siddhartha",                          "Hermann Hesse",                 "Fiction",    "978-0-81-120896-6", "Available"),
    ("Steppenwolf",                         "Hermann Hesse",                 "Fiction",    "978-0-31-237204-2", "Available"),
    ("The Trial",                           "Franz Kafka",                   "Fiction",    "978-0-80-524120-1", "Available"),
    ("The Metamorphosis",                   "Franz Kafka",                   "Fiction",    "978-0-48-629030-6", "Available"),
    ("All Quiet on the Western Front",      "Erich Maria Remarque",          "Fiction",    "978-0-34-540849-5", "Available"),
    ("The Old Man and the Sea",             "Ernest Hemingway",              "Fiction",    "978-0-68-480122-2", "Available"),
    ("Invisible Man",                       "Ralph Ellison",                 "Fiction",    "978-0-67-972020-4", "Available"),
    ("Native Son",                          "Richard Wright",                "Fiction",    "978-0-06-131249-5", "Available"),
    ("Catch-22",                            "Joseph Heller",                 "Fiction",    "978-1-45-161967-4", "Available"),
    ("Slaughterhouse-Five",                 "Kurt Vonnegut",                 "Fiction",    "978-0-38-533348-1", "Available"),
    ("Breakfast of Champions",              "Kurt Vonnegut",                 "Fiction",    "978-0-38-533348-2", "Available"),
    ("The Handmaid's Tale",                 "Margaret Atwood",               "Fiction",    "978-0-38-549081-8", "Available"),
    ("Oryx and Crake",                      "Margaret Atwood",               "Fiction",    "978-0-38-549081-9", "Available"),
    ("Never Let Me Go",                     "Kazuo Ishiguro",                "Fiction",    "978-1-40-006299-7", "Available"),
    ("The Remains of the Day",              "Kazuo Ishiguro",                "Fiction",    "978-0-67-973172-6", "Available"),
    ("Atonement",                           "Ian McEwan",                    "Fiction",    "978-0-38-572179-0", "Available"),
    ("Amsterdam",                           "Ian McEwan",                    "Fiction",    "978-0-38-549187-7", "Available"),
    ("White Noise",                         "Don DeLillo",                   "Fiction",    "978-0-14-311286-9", "Available"),
    ("Underworld",                          "Don DeLillo",                   "Fiction",    "978-0-68-484815-7", "Available"),
    ("The Corrections",                     "Jonathan Franzen",              "Fiction",    "978-0-31-242000-5", "Available"),
    ("Freedom",                             "Jonathan Franzen",              "Fiction",    "978-0-31-257640-8", "Available"),
    ("A Little Life",                       "Hanya Yanagihara",              "Fiction",    "978-0-38-539978-7", "Available"),
    ("Normal People",                       "Sally Rooney",                  "Fiction",    "978-0-57-135640-7", "Available"),
    ("Conversations with Friends",          "Sally Rooney",                  "Fiction",    "978-0-57-135639-1", "Available"),
    ("Eleanor Oliphant Is Completely Fine", "Gail Honeyman",                 "Fiction",    "978-0-00-822010-7", "Available"),
    ("Where the Crawdads Sing",             "Delia Owens",                   "Fiction",    "978-0-73-525105-1", "Available"),
    ("The Secret History",                  "Donna Tartt",                   "Fiction",    "978-0-14-017923-0", "Available"),
    ("The Goldfinch",                       "Donna Tartt",                   "Fiction",    "978-0-31-606699-9", "Available"),

    # ── FANTASY ──────────────────────────────────────────────────────────────
    ("The Hobbit",                                    "J.R.R. Tolkien",            "Fantasy",    "978-0-54-792822-7", "Available"),
    ("The Fellowship of the Ring",                    "J.R.R. Tolkien",            "Fantasy",    "978-0-54-792819-7", "Available"),
    ("The Two Towers",                                "J.R.R. Tolkien",            "Fantasy",    "978-0-54-792820-3", "Available"),
    ("The Return of the King",                        "J.R.R. Tolkien",            "Fantasy",    "978-0-54-792821-0", "Available"),
    ("Harry Potter and the Philosopher's Stone",      "J.K. Rowling",              "Fantasy",    "978-0-43-970818-8", "Available"),
    ("Harry Potter and the Chamber of Secrets",       "J.K. Rowling",              "Fantasy",    "978-0-43-970819-5", "Available"),
    ("Harry Potter and the Prisoner of Azkaban",      "J.K. Rowling",              "Fantasy",    "978-0-43-970820-1", "Available"),
    ("Harry Potter and the Goblet of Fire",           "J.K. Rowling",              "Fantasy",    "978-0-43-970821-8", "Available"),
    ("Harry Potter and the Order of the Phoenix",     "J.K. Rowling",              "Fantasy",    "978-0-43-970822-5", "Available"),
    ("Harry Potter and the Half-Blood Prince",        "J.K. Rowling",              "Fantasy",    "978-0-43-970823-2", "Available"),
    ("Harry Potter and the Deathly Hallows",          "J.K. Rowling",              "Fantasy",    "978-0-43-970824-9", "Available"),
    ("A Game of Thrones",                             "George R.R. Martin",        "Fantasy",    "978-0-55-357342-7", "Available"),
    ("A Clash of Kings",                              "George R.R. Martin",        "Fantasy",    "978-0-55-357343-4", "Available"),
    ("A Storm of Swords",                             "George R.R. Martin",        "Fantasy",    "978-0-55-357344-1", "Available"),
    ("A Feast for Crows",                             "George R.R. Martin",        "Fantasy",    "978-0-55-357345-8", "Available"),
    ("A Dance with Dragons",                          "George R.R. Martin",        "Fantasy",    "978-0-55-357346-5", "Available"),
    ("The Name of the Wind",                          "Patrick Rothfuss",          "Fantasy",    "978-0-75-640407-7", "Available"),
    ("The Wise Man's Fear",                           "Patrick Rothfuss",          "Fantasy",    "978-0-75-640408-4", "Available"),
    ("The Way of Kings",                              "Brandon Sanderson",         "Fantasy",    "978-0-76-532637-9", "Available"),
    ("Words of Radiance",                             "Brandon Sanderson",         "Fantasy",    "978-0-76-532638-6", "Available"),
    ("Oathbringer",                                   "Brandon Sanderson",         "Fantasy",    "978-0-76-532639-3", "Available"),
    ("Rhythm of War",                                 "Brandon Sanderson",         "Fantasy",    "978-0-76-532640-9", "Available"),
    ("Mistborn: The Final Empire",                    "Brandon Sanderson",         "Fantasy",    "978-0-76-531178-8", "Available"),
    ("The Well of Ascension",                         "Brandon Sanderson",         "Fantasy",    "978-0-76-531179-5", "Available"),
    ("The Hero of Ages",                              "Brandon Sanderson",         "Fantasy",    "978-0-76-531180-1", "Available"),
    ("Elantris",                                      "Brandon Sanderson",         "Fantasy",    "978-0-76-531816-9", "Available"),
    ("Warbreaker",                                    "Brandon Sanderson",         "Fantasy",    "978-0-76-531816-0", "Available"),
    ("The Lies of Locke Lamora",                      "Scott Lynch",               "Fantasy",    "978-0-55-358929-9", "Available"),
    ("Red Seas Under Red Skies",                      "Scott Lynch",               "Fantasy",    "978-0-55-358930-5", "Available"),
    ("The Blade Itself",                              "Joe Abercrombie",           "Fantasy",    "978-1-59-102594-4", "Available"),
    ("Before They Are Hanged",                        "Joe Abercrombie",           "Fantasy",    "978-1-59-102595-1", "Available"),
    ("Last Argument of Kings",                        "Joe Abercrombie",           "Fantasy",    "978-1-59-102596-8", "Available"),
    ("Eragon",                                        "Christopher Paolini",       "Fantasy",    "978-0-37-582668-8", "Available"),
    ("Eldest",                                        "Christopher Paolini",       "Fantasy",    "978-0-37-582669-5", "Available"),
    ("The Poppy War",                                 "R.F. Kuang",                "Fantasy",    "978-0-06-266245-9", "Available"),
    ("The Dragon Republic",                           "R.F. Kuang",                "Fantasy",    "978-0-06-266247-3", "Available"),
    ("Babel",                                         "R.F. Kuang",                "Fantasy",    "978-0-06-311464-3", "Available"),
    ("Dune",                                          "Frank Herbert",             "Fantasy",    "978-0-44-101781-5", "Available"),
    ("Dune Messiah",                                  "Frank Herbert",             "Fantasy",    "978-0-44-101782-2", "Available"),
    ("Children of Dune",                              "Frank Herbert",             "Fantasy",    "978-0-44-101783-9", "Available"),
    ("The Lion, the Witch and the Wardrobe",          "C.S. Lewis",                "Fantasy",    "978-0-06-447119-9", "Available"),
    ("Prince Caspian",                                "C.S. Lewis",                "Fantasy",    "978-0-06-447121-2", "Available"),
    ("The Voyage of the Dawn Treader",                "C.S. Lewis",                "Fantasy",    "978-0-06-447122-9", "Available"),
    ("American Gods",                                 "Neil Gaiman",               "Fantasy",    "978-0-38-572842-5", "Available"),
    ("Neverwhere",                                    "Neil Gaiman",               "Fantasy",    "978-0-06-102234-2", "Available"),
    ("Stardust",                                      "Neil Gaiman",               "Fantasy",    "978-0-38-072342-0", "Available"),
    ("Good Omens",                                    "Terry Pratchett & Neil Gaiman", "Fantasy","978-0-06-085398-3", "Available"),
    ("The Colour of Magic",                           "Terry Pratchett",           "Fantasy",    "978-0-06-223981-0", "Available"),
    ("Guards! Guards!",                               "Terry Pratchett",           "Fantasy",    "978-0-06-223985-8", "Available"),
    ("The Hitchhiker's Guide to the Galaxy",          "Douglas Adams",             "Fantasy",    "978-0-34-533973-9", "Available"),
    ("The Eye of the World",                          "Robert Jordan",             "Fantasy",    "978-0-81-252553-1", "Available"),
    ("The Great Hunt",                                "Robert Jordan",             "Fantasy",    "978-0-81-252554-8", "Available"),
    ("Assassin's Apprentice",                         "Robin Hobb",                "Fantasy",    "978-0-55-357341-0", "Available"),
    ("Royal Assassin",                                "Robin Hobb",                "Fantasy",    "978-0-55-358026-5", "Available"),
    ("The Black Prism",                               "Brent Weeks",               "Fantasy",    "978-0-31-606895-5", "Available"),
    ("Tigana",                                        "Guy Gavriel Kay",           "Fantasy",    "978-0-45-145129-7", "Available"),
    ("Gardens of the Moon",                           "Steven Erikson",            "Fantasy",    "978-0-76-530385-1", "Available"),
    ("The Name of the Rose",                          "Umberto Eco",               "Fantasy",    "978-0-15-144647-6", "Available"),
    ("Jonathan Strange & Mr Norrell",                 "Susanna Clarke",            "Fantasy",    "978-1-58-234416-0", "Available"),
    ("Piranesi",                                      "Susanna Clarke",            "Fantasy",    "978-1-63-557692-1", "Available"),
    ("The Once and Future King",                      "T.H. White",                "Fantasy",    "978-0-44-162740-7", "Available"),
    ("The Princess Bride",                            "William Goldman",           "Fantasy",    "978-0-15-602831-3", "Available"),
    ("Perdido Street Station",                        "China Miéville",            "Fantasy",    "978-0-34-542619-2", "Available"),
    ("The City & The City",                           "China Miéville",            "Fantasy",    "978-0-34-549764-3", "Available"),
    ("The Night Circus",                              "Erin Morgenstern",          "Fantasy",    "978-0-38-553463-5", "Available"),
    ("Circe",                                         "Madeline Miller",           "Fantasy",    "978-0-31-655690-7", "Available"),
    ("The Song of Achilles",                          "Madeline Miller",           "Fantasy",    "978-0-06-206726-4", "Available"),

    # ── HORROR ───────────────────────────────────────────────────────────────
    ("It",                                    "Stephen King",              "Horror",     "978-1-50-115311-7", "Available"),
    ("The Shining",                           "Stephen King",              "Horror",     "978-0-38-508807-6", "Available"),
    ("Pet Sematary",                          "Stephen King",              "Horror",     "978-1-50-115317-9", "Available"),
    ("The Stand",                             "Stephen King",              "Horror",     "978-0-38-580823-2", "Available"),
    ("Misery",                                "Stephen King",              "Horror",     "978-0-45-014130-0", "Available"),
    ("Carrie",                                "Stephen King",              "Horror",     "978-0-38-533976-1", "Available"),
    ("Christine",                             "Stephen King",              "Horror",     "978-0-45-114044-4", "Available"),
    ("Cujo",                                  "Stephen King",              "Horror",     "978-0-45-213547-8", "Available"),
    ("Doctor Sleep",                          "Stephen King",              "Horror",     "978-1-47-113026-6", "Available"),
    ("The Dark Tower: The Gunslinger",        "Stephen King",              "Horror",     "978-1-45-161027-6", "Available"),
    ("Salem's Lot",                           "Stephen King",              "Horror",     "978-0-38-550058-8", "Available"),
    ("Night Shift",                           "Stephen King",              "Horror",     "978-0-38-508927-1", "Available"),
    ("Skeleton Crew",                         "Stephen King",              "Horror",     "978-0-45-116045-9", "Available"),
    ("Dracula",                               "Bram Stoker",               "Horror",     "978-0-14-143984-6", "Available"),
    ("Frankenstein",                          "Mary Shelley",              "Horror",     "978-0-14-143947-1", "Available"),
    ("The Haunting of Hill House",            "Shirley Jackson",           "Horror",     "978-0-14-303998-2", "Available"),
    ("We Have Always Lived in the Castle",    "Shirley Jackson",           "Horror",     "978-0-14-303997-5", "Available"),
    ("House of Leaves",                       "Mark Z. Danielewski",       "Horror",     "978-0-37-570376-1", "Available"),
    ("The Call of Cthulhu",                   "H.P. Lovecraft",            "Horror",     "978-0-14-243722-3", "Available"),
    ("At the Mountains of Madness",           "H.P. Lovecraft",            "Horror",     "978-0-14-243763-6", "Available"),
    ("The Shadow Over Innsmouth",             "H.P. Lovecraft",            "Horror",     "978-0-14-243764-3", "Available"),
    ("The Colour Out of Space",               "H.P. Lovecraft",            "Horror",     "978-0-14-243765-0", "Available"),
    ("Interview with the Vampire",            "Anne Rice",                 "Horror",     "978-0-34-533987-6", "Available"),
    ("The Vampire Lestat",                    "Anne Rice",                 "Horror",     "978-0-34-541549-7", "Available"),
    ("Queen of the Damned",                   "Anne Rice",                 "Horror",     "978-0-34-541550-3", "Available"),
    ("Strange Case of Dr Jekyll and Mr Hyde", "Robert Louis Stevenson",    "Horror",     "978-0-14-143976-1", "Available"),
    ("The Turn of the Screw",                 "Henry James",               "Horror",     "978-0-14-143956-4", "Available"),
    ("Rosemary's Baby",                       "Ira Levin",                 "Horror",     "978-0-45-116538-6", "Available"),
    ("The Stepford Wives",                    "Ira Levin",                 "Horror",     "978-1-40-007985-8", "Available"),
    ("The Exorcist",                          "William Peter Blatty",      "Horror",     "978-0-06-131285-3", "Available"),
    ("Silence of the Lambs",                  "Thomas Harris",             "Horror",     "978-0-31-292458-4", "Available"),
    ("Red Dragon",                            "Thomas Harris",             "Horror",     "978-0-42-519066-0", "Available"),
    ("Hell House",                            "Richard Matheson",          "Horror",     "978-0-76-530353-0", "Available"),
    ("I Am Legend",                           "Richard Matheson",          "Horror",     "978-0-76-530321-9", "Available"),
    ("Something Wicked This Way Comes",       "Ray Bradbury",              "Horror",     "978-0-68-081032-5", "Available"),
    ("Bird Box",                              "Josh Malerman",             "Horror",     "978-0-06-227322-8", "Available"),
    ("Mexican Gothic",                        "Silvia Moreno-Garcia",      "Horror",     "978-0-52-557990-5", "Available"),
    ("NOS4A2",                                "Joe Hill",                  "Horror",     "978-0-06-220653-7", "Available"),
    ("Heart-Shaped Box",                      "Joe Hill",                  "Horror",     "978-0-06-114793-0", "Available"),
    ("Horns",                                 "Joe Hill",                  "Horror",     "978-0-06-114794-7", "Available"),
    ("The Troop",                             "Nick Cutter",               "Horror",     "978-1-47-678279-0", "Available"),
    ("Tender is the Flesh",                   "Agustina Bazterrica",       "Horror",     "978-1-25-023895-4", "Available"),
    ("The Only Good Indians",                 "Stephen Graham Jones",      "Horror",     "978-1-98-219782-4", "Available"),
    ("The Hellbound Heart",                   "Clive Barker",              "Horror",     "978-0-06-100604-5", "Available"),
    ("Books of Blood Vol. 1",                 "Clive Barker",              "Horror",     "978-0-84-397250-1", "Available"),
    ("Ghost Story",                           "Peter Straub",              "Horror",     "978-0-67-172562-0", "Available"),
    ("Bag of Bones",                          "Stephen King",              "Horror",     "978-0-74-323243-6", "Available"),
    ("Needful Things",                        "Stephen King",              "Horror",     "978-0-45-170461-5", "Available"),
    ("The Ritual",                            "Adam Nevill",               "Horror",     "978-1-44-807285-6", "Available"),
    ("The Fisherman",                         "John Langan",               "Horror",     "978-0-98-498374-0", "Available"),
    ("The Monk",                              "Matthew Lewis",             "Horror",     "978-0-19-953668-3", "Available"),
    ("The Wasp Factory",                      "Iain Banks",                "Horror",     "978-0-34-903706-6", "Available"),
    ("World War Z",                           "Max Brooks",                "Horror",     "978-0-30-735610-0", "Available"),
    ("The Walking Dead Vol. 1",               "Robert Kirkman",            "Horror",     "978-1-58-240358-3", "Available"),
    ("Plain Bad Heroines",                    "Emily M. Danforth",         "Horror",     "978-0-06-286997-8", "Available"),

    # ── TECHNOLOGY / AI ──────────────────────────────────────────────────────
    ("Artificial Intelligence: A Modern Approach", "Stuart Russell & Peter Norvig", "Technology", "978-0-13-461099-3", "Available"),
    ("Deep Learning",                         "Ian Goodfellow et al.",     "Technology", "978-0-26-203561-3", "Available"),
    ("The Singularity Is Near",               "Ray Kurzweil",              "Technology", "978-0-14-303989-0", "Available"),
    ("The Age of Spiritual Machines",         "Ray Kurzweil",              "Technology", "978-0-14-028202-2", "Available"),
    ("Superintelligence",                     "Nick Bostrom",              "Technology", "978-0-19-967811-2", "Available"),
    ("Human Compatible",                      "Stuart Russell",            "Technology", "978-0-52-555861-3", "Available"),
    ("Life 3.0",                              "Max Tegmark",               "Technology", "978-0-52-557352-1", "Available"),
    ("The Alignment Problem",                 "Brian Christian",           "Technology", "978-0-39-318173-4", "Available"),
    ("Weapons of Math Destruction",           "Cathy O'Neil",              "Technology", "978-0-55-341881-1", "Available"),
    ("The Age of Surveillance Capitalism",    "Shoshana Zuboff",           "Technology", "978-1-61-039569-4", "Available"),
    ("Atlas of AI",                           "Kate Crawford",             "Technology", "978-0-30-020957-8", "Available"),
    ("AI Superpowers",                        "Kai-Fu Lee",                "Technology", "978-0-35-845302-7", "Available"),
    ("The Coming Wave",                       "Mustafa Suleyman",          "Technology", "978-0-59-365730-7", "Available"),
    ("Our Final Invention",                   "James Barrat",              "Technology", "978-0-31-230232-0", "Available"),
    ("The Code Breaker",                      "Walter Isaacson",           "Technology", "978-1-98-214723-3", "Available"),
    ("The Innovators",                        "Walter Isaacson",           "Technology", "978-1-47-673791-4", "Available"),
    ("Hackers",                               "Steven Levy",               "Technology", "978-1-44-933012-6", "Available"),
    ("The Dream Machine",                     "M. Mitchell Waldrop",       "Technology", "978-1-73-265289-3", "Available"),
    ("Turing's Cathedral",                    "George Dyson",              "Technology", "978-0-37-542277-5", "Available"),
    ("Clean Code",                            "Robert C. Martin",          "Technology", "978-0-13-235088-4", "Available"),
    ("The Pragmatic Programmer",              "David Thomas & Andrew Hunt","Technology", "978-0-13-595705-9", "Available"),
    ("Design Patterns",                       "Erich Gamma et al.",        "Technology", "978-0-20-163361-5", "Available"),
    ("The Mythical Man-Month",                "Frederick P. Brooks Jr.",   "Technology", "978-0-20-183595-3", "Available"),
    ("Introduction to Algorithms",            "Thomas H. Cormen et al.",   "Technology", "978-0-26-204630-5", "Available"),
    ("Pattern Recognition and Machine Learning","Christopher Bishop",      "Technology", "978-0-38-731073-2", "Available"),
    ("Hands-On Machine Learning",             "Aurélien Géron",            "Technology", "978-1-09-812029-8", "Available"),
    ("The Book of Why",                       "Judea Pearl & Dana Mackenzie","Technology","978-0-46-509760-9", "Available"),
    ("Gödel, Escher, Bach",                   "Douglas Hofstadter",        "Technology", "978-0-46-502656-2", "Available"),
    ("The Information",                       "James Gleick",              "Technology", "978-0-37-542372-7", "Available"),
    ("The Second Machine Age",                "Erik Brynjolfsson & Andrew McAfee","Technology","978-0-39-335064-6","Available"),
    ("The Phoenix Project",                   "Gene Kim et al.",           "Technology", "978-1-94-278839-7", "Available"),
    ("Zero to One",                           "Peter Thiel & Blake Masters","Technology","978-0-80-419416-4", "Available"),
    ("The Lean Startup",                      "Eric Ries",                 "Technology", "978-0-30-788191-7", "Available"),
    ("Steve Jobs",                            "Walter Isaacson",           "Technology", "978-1-45-168342-2", "Available"),
    ("Elon Musk",                             "Walter Isaacson",           "Technology", "978-1-98-218562-3", "Available"),
    ("The Fourth Industrial Revolution",      "Klaus Schwab",              "Technology", "978-1-52-661024-0", "Available"),
    ("Homo Deus",                             "Yuval Noah Harari",         "Technology", "978-0-06-246431-6", "Available"),
    ("Power and Prediction",                  "Ajay Agrawal et al.",       "Technology", "978-1-64-782038-9", "Available"),
    ("The Precipice",                         "Toby Ord",                  "Technology", "978-0-31-625520-3", "Available"),
    ("Data Feminism",                         "Catherine D'Ignazio & Lauren Klein","Technology","978-0-26-203700-6","Available"),
    ("Code",                                  "Charles Petzold",           "Technology", "978-0-73-560505-0", "Available"),
    ("Structure & Interpretation of Computer Programs","Harold Abelson",   "Technology", "978-0-26-204630-4", "Available"),
    ("Chaos Monkeys",                         "Antonio García Martínez",   "Technology", "978-0-06-243812-9", "Available"),
    ("No Filter",                             "Sarah Frier",               "Technology", "978-1-98-218533-3", "Available"),
    ("Refactoring",                           "Martin Fowler",             "Technology", "978-0-13-468599-1", "Available"),
    ("Machine Learning Yearning",             "Andrew Ng",                 "Technology", "978-1-40-578629-1", "Available"),
    ("Mathematics for Machine Learning",      "Marc Peter Deisenroth et al.","Technology","978-1-10-845514-5","Available"),
    ("The Algorithm",                         "Hilke Schellmann",          "Technology", "978-1-54-609978-0", "Available"),
    ("Prediction Machines",                   "Ajay Agrawal et al.",       "Technology", "978-1-63-369322-6", "Available"),
    ("The Master Algorithm",                  "Pedro Domingos",            "Technology", "978-0-46-506570-7", "Available"),

    # ── SCIENCE ──────────────────────────────────────────────────────────────
    ("A Brief History of Time",               "Stephen Hawking",           "Science",    "978-0-55-317565-3", "Available"),
    ("The Selfish Gene",                      "Richard Dawkins",           "Science",    "978-0-19-929115-2", "Available"),
    ("Cosmos",                                "Carl Sagan",                "Science",    "978-0-34-533957-9", "Available"),
    ("The Elegant Universe",                  "Brian Greene",              "Science",    "978-0-39-333810-4", "Available"),
    ("The Fabric of the Cosmos",              "Brian Greene",              "Science",    "978-0-37-572811-9", "Available"),
    ("Pale Blue Dot",                         "Carl Sagan",                "Science",    "978-0-34-537596-8", "Available"),
    ("The Double Helix",                      "James D. Watson",           "Science",    "978-0-74-327281-9", "Available"),
    ("The God Delusion",                      "Richard Dawkins",           "Science",    "978-0-61-861523-9", "Available"),
    ("The Demon-Haunted World",               "Carl Sagan",                "Science",    "978-0-34-540946-1", "Available"),
    ("Astrophysics for People in a Hurry",    "Neil deGrasse Tyson",       "Science",    "978-0-39-360939-4", "Available"),
    ("The Hidden Life of Trees",              "Peter Wohlleben",           "Science",    "978-0-00-826484-5", "Available"),
    ("The Sixth Extinction",                  "Elizabeth Kolbert",         "Science",    "978-0-80-502090-0", "Available"),
    ("The Gene",                              "Siddhartha Mukherjee",      "Science",    "978-1-47-670356-5", "Available"),
    ("The Emperor of All Maladies",           "Siddhartha Mukherjee",      "Science",    "978-1-43-916432-4", "Available"),
    ("Being Mortal",                          "Atul Gawande",              "Science",    "978-1-62-779055-5", "Available"),
    ("The Body",                              "Bill Bryson",               "Science",    "978-0-38-554005-5", "Available"),
    ("A Short History of Nearly Everything",  "Bill Bryson",               "Science",    "978-0-76-790818-7", "Available"),
    ("The Immortal Life of Henrietta Lacks",  "Rebecca Skloot",            "Science",    "978-1-40-005218-9", "Available"),
    ("The Structure of Scientific Revolutions","Thomas S. Kuhn",           "Science",    "978-0-22-645811-3", "Available"),
    ("What Is Life?",                         "Erwin Schrödinger",         "Science",    "978-0-52-142708-5", "Available"),
    ("The Origin of Species",                 "Charles Darwin",            "Science",    "978-0-14-043205-6", "Available"),
    ("Chaos",                                 "James Gleick",              "Science",    "978-0-14-303799-5", "Available"),
    ("The Big Picture",                       "Sean Carroll",              "Science",    "978-0-52-595440-1", "Available"),
    ("Something Deeply Hidden",               "Sean Carroll",              "Science",    "978-1-52-476301-3", "Available"),
    ("Seven Brief Lessons on Physics",        "Carlo Rovelli",             "Science",    "978-0-73-522867-1", "Available"),
    ("The Order of Time",                     "Carlo Rovelli",             "Science",    "978-0-73-523657-7", "Available"),
    ("Reality Is Not What It Seems",          "Carlo Rovelli",             "Science",    "978-0-73-523358-3", "Available"),
    ("Brief Answers to the Big Questions",    "Stephen Hawking",           "Science",    "978-1-98-183478-8", "Available"),
    ("The Grand Design",                      "Stephen Hawking",           "Science",    "978-0-55-381929-4", "Available"),
    ("Behave",                                "Robert M. Sapolsky",        "Science",    "978-1-59-420191-3", "Available"),

    # ── HISTORY ──────────────────────────────────────────────────────────────
    ("Sapiens: A Brief History of Humankind", "Yuval Noah Harari",         "History",    "978-0-06-231609-8", "Available"),
    ("21 Lessons for the 21st Century",       "Yuval Noah Harari",         "History",    "978-0-52-557850-2", "Available"),
    ("Guns, Germs, and Steel",                "Jared Diamond",             "History",    "978-0-39-331755-8", "Available"),
    ("The Rise and Fall of the Third Reich",  "William L. Shirer",         "History",    "978-0-44-131770-9", "Available"),
    ("The Diary of a Young Girl",             "Anne Frank",                "History",    "978-0-55-358427-0", "Available"),
    ("Night",                                 "Elie Wiesel",               "History",    "978-0-37-490001-1", "Available"),
    ("Man's Search for Meaning",              "Viktor Frankl",             "History",    "978-0-80-701429-5", "Available"),
    ("The Art of War",                        "Sun Tzu",                   "History",    "978-1-59-030963-7", "Available"),
    ("1776",                                  "David McCullough",          "History",    "978-0-74-326998-7", "Available"),
    ("Team of Rivals",                        "Doris Kearns Goodwin",      "History",    "978-0-74-327193-5", "Available"),
    ("Alexander Hamilton",                    "Ron Chernow",               "History",    "978-0-14-303475-8", "Available"),
    ("The Wright Brothers",                   "David McCullough",          "History",    "978-1-47-672377-1", "Available"),
    ("Unbroken",                              "Laura Hillenbrand",         "History",    "978-1-40-007339-9", "Available"),
    ("The Devil in the White City",           "Erik Larson",               "History",    "978-0-37-572560-6", "Available"),
    ("Dead Wake",                             "Erik Larson",               "History",    "978-0-30-740677-8", "Available"),
    ("In the Heart of the Sea",               "Nathaniel Philbrick",       "History",    "978-0-14-200182-5", "Available"),
    ("The Warmth of Other Suns",              "Isabel Wilkerson",          "History",    "978-0-67-976978-5", "Available"),
    ("Caste",                                 "Isabel Wilkerson",          "History",    "978-0-59-344818-0", "Available"),
    ("The Silk Roads",                        "Peter Frankopan",           "History",    "978-1-10-187067-4", "Available"),
    ("SPQR",                                  "Mary Beard",                "History",    "978-1-63-149011-4", "Available"),
    ("The Histories",                         "Herodotus",                 "History",    "978-0-14-044908-2", "Available"),
    ("The History of the Peloponnesian War",  "Thucydides",               "History",    "978-0-14-044039-3", "Available"),
    ("The Prince",                            "Niccolò Machiavelli",       "History",    "978-0-14-044915-0", "Available"),
    ("Destiny of the Republic",               "Candice Millard",           "History",    "978-0-38-553001-9", "Available"),
    ("The River of Doubt",                    "Candice Millard",           "History",    "978-0-76-792242-8", "Available"),
    ("Hiroshima",                             "John Hersey",               "History",    "978-0-67-972197-0", "Available"),
    ("The Guns of August",                    "Barbara W. Tuchman",        "History",    "978-0-34-538623-4", "Available"),
    ("A World Undone",                        "G.J. Meyer",                "History",    "978-0-55-338898-6", "Available"),
    ("The Splendid and the Vile",             "Erik Larson",               "History",    "978-0-38-534880-0", "Available"),
    ("Empire of the Summer Moon",             "S.C. Gwynne",               "History",    "978-1-41-657816-0", "Available"),

    # ── NON-FICTION ──────────────────────────────────────────────────────────
    ("Atomic Habits",                         "James Clear",               "Non-Fiction","978-0-73-521429-2", "Available"),
    ("The 7 Habits of Highly Effective People","Stephen R. Covey",         "Non-Fiction","978-0-74-325601-4", "Available"),
    ("How to Win Friends and Influence People","Dale Carnegie",            "Non-Fiction","978-0-67-142517-9", "Available"),
    ("Thinking, Fast and Slow",               "Daniel Kahneman",           "Non-Fiction","978-0-37-453355-7", "Available"),
    ("Outliers",                              "Malcolm Gladwell",          "Non-Fiction","978-0-31-601792-9", "Available"),
    ("The Tipping Point",                     "Malcolm Gladwell",          "Non-Fiction","978-0-31-634662-7", "Available"),
    ("Blink",                                 "Malcolm Gladwell",          "Non-Fiction","978-0-31-634769-3", "Available"),
    ("Talking to Strangers",                  "Malcolm Gladwell",          "Non-Fiction","978-0-31-647987-8", "Available"),
    ("The Power of Now",                      "Eckhart Tolle",             "Non-Fiction","978-1-57-731480-3", "Available"),
    ("A New Earth",                           "Eckhart Tolle",             "Non-Fiction","978-0-45-229302-7", "Available"),
    ("The Subtle Art of Not Giving a F*ck",   "Mark Manson",               "Non-Fiction","978-0-06-245771-5", "Available"),
    ("Everything Is F*cked",                  "Mark Manson",               "Non-Fiction","978-0-06-287639-6", "Available"),
    ("Educated",                              "Tara Westover",             "Non-Fiction","978-0-39-959051-2", "Available"),
    ("Becoming",                              "Michelle Obama",            "Non-Fiction","978-1-52-476313-6", "Available"),
    ("The Glass Castle",                      "Jeannette Walls",           "Non-Fiction","978-0-74-326768-6", "Available"),
    ("Born a Crime",                          "Trevor Noah",               "Non-Fiction","978-0-39-958516-7", "Available"),
    ("When Breath Becomes Air",               "Paul Kalanithi",            "Non-Fiction","978-0-81-299963-3", "Available"),
    ("Option B",                              "Sheryl Sandberg & Adam Grant","Non-Fiction","978-1-52-476105-7","Available"),
    ("Lean In",                               "Sheryl Sandberg",           "Non-Fiction","978-0-38-534974-6", "Available"),
    ("Deep Work",                             "Cal Newport",               "Non-Fiction","978-1-45-555430-4", "Available"),
    ("Digital Minimalism",                    "Cal Newport",               "Non-Fiction","978-0-52-555851-4", "Available"),
    ("So Good They Can't Ignore You",         "Cal Newport",               "Non-Fiction","978-1-45-555427-4", "Available"),
    ("Quiet",                                 "Susan Cain",                "Non-Fiction","978-0-30-788370-6", "Available"),
    ("Drive",                                 "Daniel H. Pink",            "Non-Fiction","978-1-59-448884-9", "Available"),
    ("To Sell Is Human",                      "Daniel H. Pink",            "Non-Fiction","978-1-59-448756-9", "Available"),
    ("The 4-Hour Workweek",                   "Tim Ferriss",               "Non-Fiction","978-0-30-727389-5", "Available"),
    ("Tools of Titans",                       "Tim Ferriss",               "Non-Fiction","978-1-32-839457-3", "Available"),
    ("The Power of Habit",                    "Charles Duhigg",            "Non-Fiction","978-0-81-298160-7", "Available"),
    ("Smarter Faster Better",                 "Charles Duhigg",            "Non-Fiction","978-0-81-298160-8", "Available"),
    ("Rich Dad Poor Dad",                     "Robert T. Kiyosaki",        "Non-Fiction","978-1-61-259411-4", "Available"),

    # ── MYSTERY ──────────────────────────────────────────────────────────────
    ("The Girl with the Dragon Tattoo",       "Stieg Larsson",             "Mystery",    "978-0-30-726975-1", "Available"),
    ("The Girl Who Played with Fire",         "Stieg Larsson",             "Mystery",    "978-0-30-726976-8", "Available"),
    ("Gone Girl",                             "Gillian Flynn",             "Mystery",    "978-0-30-758845-1", "Available"),
    ("Sharp Objects",                         "Gillian Flynn",             "Mystery",    "978-0-30-734507-6", "Available"),
    ("Dark Places",                           "Gillian Flynn",             "Mystery",    "978-0-30-734508-3", "Available"),
    ("Big Little Lies",                       "Liane Moriarty",            "Mystery",    "978-0-39-916768-6", "Available"),
    ("Nine Perfect Strangers",                "Liane Moriarty",            "Mystery",    "978-1-47-502867-0", "Available"),
    ("The Thursday Murder Club",              "Richard Osman",             "Mystery",    "978-0-24-143916-2", "Available"),
    ("In the Woods",                          "Tana French",               "Mystery",    "978-0-14-311418-4", "Available"),
    ("The Likeness",                          "Tana French",               "Mystery",    "978-0-14-311757-4", "Available"),
    ("And Then There Were None",              "Agatha Christie",           "Mystery",    "978-0-06-207349-4", "Available"),
    ("Murder on the Orient Express",          "Agatha Christie",           "Mystery",    "978-0-06-207350-0", "Available"),
    ("Death on the Nile",                     "Agatha Christie",           "Mystery",    "978-0-06-207351-7", "Available"),
    ("The Hound of the Baskervilles",         "Arthur Conan Doyle",        "Mystery",    "978-0-14-043786-0", "Available"),
    ("A Study in Scarlet",                    "Arthur Conan Doyle",        "Mystery",    "978-0-14-043787-7", "Available"),
    ("The Adventures of Sherlock Holmes",     "Arthur Conan Doyle",        "Mystery",    "978-0-14-043788-4", "Available"),
    ("The Name of the Rose",                  "Umberto Eco",               "Mystery",    "978-0-15-144647-7", "Available"),
    ("The Big Sleep",                         "Raymond Chandler",          "Mystery",    "978-0-39-445771-4", "Available"),
    ("The Maltese Falcon",                    "Dashiell Hammett",          "Mystery",    "978-0-67-972264-9", "Available"),
    ("Rebecca",                               "Daphne du Maurier",         "Mystery",    "978-0-38-054090-7", "Available"),
]


def seed():
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}")
        print("Start the backend server first so it creates the database, then run this script.")
        return

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    # Get existing ISBNs to avoid duplicates
    cur.execute("SELECT isbn FROM books")
    existing_isbns = {row[0] for row in cur.fetchall()}

    inserted = 0
    skipped = 0

    for title, author, category, isbn, status in BOOKS:
        if isbn in existing_isbns:
            skipped += 1
            continue
        cur.execute(
            "INSERT INTO books (title, author, category, isbn, availability_status) VALUES (?, ?, ?, ?, ?)",
            (title, author, category, isbn, status)
        )
        existing_isbns.add(isbn)
        inserted += 1

    conn.commit()
    conn.close()

    print(f"Seeding complete!")
    print(f"  Inserted : {inserted} books")
    print(f"  Skipped  : {skipped} (already existed)")
    print(f"  Total now: {inserted + skipped} entries processed")


if __name__ == "__main__":
    seed()
